name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: /root/.jbang
          key: ${{ runner.os }}-jbang-${{ hashFiles('*.java') }}
          restore-keys: |
            ${{ runner.os }}-jbang-
      - uses: actions/setup-java@v1
        with:
          java-version: '11'            
      - name: jbang build
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - export -O kubeno.jar src/main/java/kubeno.java
          ls -l